{% set name = "opentelemetry-instrumentation-logging" %}
{% set version = "0.38b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_logging-{{ version }}.tar.gz
  sha256: ab3c3fb671336dd11c182a73d245c8bfb1b249af5a009ae88e582453c2336009

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.38b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-test-utils ==0.38b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/master/instrumentation/opentelemetry-instrumentation-logging
  summary: OpenTelemetry Logging instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
